config/routes.rb
Rails.application.routes.draw do
  get 'notifications/index'
  get 'rooms/show'
  get 'events/index'
  devise_for :users , controllers: {
    sessions: 'users/sessions',
    passwords: 'users/passwords',
    registrations: 'users/registrations'
  }
  devise_for :admins, controllers: {
    sessions: 'admins/sessions',
    passwords: 'admins/passwords',
    registrations: 'admins/registrations'
  }

  namespace :admins do
    get "prefectures/search" => "prefectures#search"
    resources :prefectures, only: [:index, :show, :create ]
    get 'contacts/top' => "contacts#top"
    resources :contacts, except: :show
    resources :language_tags, except: :show
    resources :framework_tags, except: :show
    resources :companies
    resources :post_comments, only: [:index, :show, :destroy]
  end
  namespace :api, format: 'json' do
    resources :memos, only: [:index, :create, :destroy, :update]
    resources :tasks, only: [:index, :create, :update, :destroy]
  end

  root to: 'homes#top'
  get "homes/about" => "homes#about"
  get "homes/memo" => "homes#memo"
  get "homes/community" => "homes#community"
  get "homes/task" => "homes#task"
  get "task_about" => "contacts#task"
  get "task_top" => "contacts#task"
  get "prefectures/search" => "prefectures#search"
  resources :contacts, only: [:new, :create]
  resources :prefectures, only: [:index, :show]
  resources :companies, only: :show do
    resources :post_comments, except: [:index ,:show]
  end
  resources :events
  resources :users, only: :show
  resources :communities, only: [:index, :show, :create ,:destroy] do
    resource :likes, only: [:create, :destroy]
  end
  resources :chat_rooms, only: [:show, :create ]
  resources :chat_messages, only: :create
  resources :notifications, only: [:index]
  delete "notifications/destroy_all" => "notifications#destroy_all"

  mount ActionCable.server => '/cable'
end

app/models/notification.rb
class Notification < ApplicationRecord
  default_scope->{order(created_at: :desc)}

  belongs_to :chat_room, optional: true
  belongs_to :chat_message, optional: true
  belongs_to :visitor, class_name: 'User', foreign_key: 'visitor_id', optional: true
  belongs_to :visited, class_name: 'User', foreign_key: 'visited_id', optional: true
end

app/controllers/notifications_controller.rb
class NotificationsController < ApplicationController
  def index
    @notifications = current_user.passive_notifications.page(params[:page]).per(20)
    @notifications.where(checked: false).each do |notification|
      notification.update_attributes(checked: true)
    end
  end

  def destroy_all
    notifications = current_user.passive_notifications
    if notifications.destroy_all
      redirect_to notifications_path
    end
  end
end

app/helpers/notifications_helper.rb
module NotificationsHelper
  def unchecked_notifications
    @notifications = current_user.passive_notifications.where(checked: false)
  end
end

app/views/notifications/_notification.html.erb
<% visitor = notification.visitor %>
<% visited = notification.visited %>
<div class="notifications__messages">
  <% if visitor.profile_image? %>
  <%= image_tag visitor.profile_image.url ,class: 'visitor-img' %>
  <% else %>
  <div class="user-default-img"></div>
  <% end %>
  <div class="notifications__message">
    <%= link_to user_path(visitor) do %>
    <%= visitor.name %>さん
    <% end %>
    <% if  notification.action === 'chat' %>
    <span>から <%= link_to "メッセージ", chat_rooms_path( params: {user_id: visitor}) , method: :post%> がきました
      <%= " (#{time_ago_in_words(notification.created_at)} 前)" %></span>
    <div></div>
    <% end %>
  </div>
</div>

app/views/notifications/index.html.erb
  <div class="wrapper">
    <div class="wrapper__inner">
      <div class="notifications">
        <div class="notifications__header">
          <nav>
            <%= link_to :back do %>
            <i class="fas fa-chevron-left"></i>
            <% end %>
          </nav>
          <nav class="notifications__nav-center">
            notification
          </nav>
          <nav class="notifications__nav-right">
            <%= link_to '全削除' ,notifications_destroy_all_path ,method: :delete %>
          </nav>
        </div>

        <% notifications = @notifications.where.not(visitor_id: current_user.id) %>
        <% if notifications.exists? %>
        <%= render notifications  %>
        <% else %>
        <p class="notifications__elsemessage">現在、通知メッセージはありません</p>
        <% end %>
      </div>
    </div>
  </div>