config/routes.rb
Rails.application.routes.draw do
  get 'notifications/index'
  get 'rooms/show'
  get 'events/index'
  devise_for :users , controllers: {
    sessions: 'users/sessions',
    passwords: 'users/passwords',
    registrations: 'users/registrations'
  }
  devise_for :admins, controllers: {
    sessions: 'admins/sessions',
    passwords: 'admins/passwords',
    registrations: 'admins/registrations'
  }

  namespace :admins do
    get "prefectures/search" => "prefectures#search"
    resources :prefectures, only: [:index, :show, :create ]
    get 'contacts/top' => "contacts#top"
    resources :contacts, except: :show
    resources :language_tags, except: :show
    resources :framework_tags, except: :show
    resources :companies
    resources :post_comments, only: [:index, :show, :destroy]
  end
  namespace :api, format: 'json' do
    resources :memos, only: [:index, :create, :destroy, :update]
    resources :tasks, only: [:index, :create, :update, :destroy]
  end

  root to: 'homes#top'
  get "homes/about" => "homes#about"
  get "homes/memo" => "homes#memo"
  get "homes/community" => "homes#community"
  get "homes/task" => "homes#task"
  get "task_about" => "contacts#task"
  get "task_top" => "contacts#task"
  get "prefectures/search" => "prefectures#search"
  resources :contacts, only: [:new, :create]
  resources :prefectures, only: [:index, :show]
  resources :companies, only: :show do
    resources :post_comments, except: [:index ,:show]
  end
  resources :events
  resources :users, only: :show
  resources :communities, only: [:index, :show, :create ,:destroy] do
    resource :likes, only: [:create, :destroy]
  end
  resources :chat_rooms, only: [:show, :create ]
  resources :chat_messages, only: :create
  resources :notifications, only: [:index]
  delete "notifications/destroy_all" => "notifications#destroy_all"

  mount ActionCable.server => '/cable'
end

app/models/contact.rb
class Contact < ApplicationRecord
  belongs_to :user
  validates :title, presence: true
  validates :body, presence: true
end

app/controllers/admins/contacts_controller.rb
class Admins::ContactsController < ApplicationController
  before_action :authenticate_admin!
  def top
  end

  def index
    @contacts = Contact.page(params[:page]).order(created_at: :desc).per(10)
  end

  def edit
    @contact = Contact.find(params[:id])
  end

  def update
    @contact = Contact.find(params[:id])
    if @contact.update(contacts_params)
      flash[:notice] = '返信できました'
      user = @contact.user
      ContactMailer.send_when_admin_reply(user, @contact).deliver_now
      redirect_to admins_contacts_path
    else
      render :edit
    end
  end

  def destroy
    contact = Contact.find(params[:id])
    if contact.destroy
      redirect_to admins_contacts_path
    end
  end

  private

  def contacts_params
    params.require(:contact).permit(:title, :body, :reply)
  end
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  before_action :authenticate_user!
  def new
    @contact = Contact.new
  end

  def create
    @contact = Contact.new(contacts_params)
    @contact.user_id = current_user.id
    if @contact.save
      flash[:notice] = 'お問い合わせを送信しました。'
      redirect_to root_path
    else
      render :new
    end
  end

  private

  def contacts_params
    params.require(:contact).permit(:title, :body, :reply)
  end
end

app/views/admins/contacts/edit.html.erb
<div class="wrapper">
  <div class="wrapper__inner">
    <% if @contact.errors.any? %>
    <%= @contact.errors.count %>件のエラー。
    <% @contact.errors.full_messages.each do |message| %>
    <%= message %>
    <% end %>
    <% end %>
    <div class="company-post">
      <div class="company-post__inner">
        <%= form_for @contact, url: admins_contact_path do |f| %>
        <div class="company-post__title">
          <h2>お問い合わせ返信ページ</h2>
        </div>
        <div class="company-post__items">
          <div>ユーザー名</div>
          <%= @contact.user.name %>様
          <div>受信日</div>
          <%= @contact.created_at.strftime("%Y年%m月%d日 ") %>
          <div>お問い合わせ内容</div>
          <%= @contact.body %>
          <div>返信</div>
          <%= f.text_area :body ,class: 'description-area'%>
        </div>
        <%= f.submit 'Send', class: 'btn solid'%>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/admins/contacts/index.html.erb
<div class="wrapper">
  <div class="contact">
    <div class="contact__title main-title">お問い合わせ一覧</div>
    <table class="table">
      <thead>
        <tr>
          <th>ユーザー名</th>
          <th>受信日</th>
          <th>件名</th>
          <th></th>
          <th colspan="2"></th>
        </tr>
      </thead>
      <tbody>
        <% @contacts.each do |contact| %>
        <tr>
          <td><%= contact.user.name %> さま</td>
          <td><%= contact.created_at.strftime("%Y年%m月%d日 ") %></td>
          <p>
            <td><%= contact.title %></td>
          </p>

          <td><%= link_to "返信", edit_admins_contact_path(contact) %></td>
          <td><%= link_to "削除", admins_contact_path(contact), method: :delete, data: {confirm: "Are you sure?"} %></td>
        </tr>
        <% end %>
      </tbody>
    </table>
    <%= paginate @contacts %>
  </div>
</div>

app/views/admins/contacts/top.html.erb
<div class="wrapper">
  <div class="admin-top">
    <div class="items">
      <div class="items__inner">
        <%= link_to  admins_contacts_path do %>
        <div class="item">
          <p>Mail</p>
          <p>メールの確認・返信</p>
        </div>
        <% end %>
      </div>
      <div class="items__inner">
        <%= link_to admins_post_comments_path do %>
        <div class="item">
          <p>Reviews</p>
          <p>Reviewの確認・削除</p>
        </div>
        <% end %>
      </div>
      <div class="items__inner">
        <%= link_to admins_prefectures_path do %>
        <div class="item">
          <p>Company</p>
          <p>掲載企業の追加・変更</p>
        </div>
        <% end %>
      </div>
      <div class="items__inner">
        <%= link_to admins_language_tags_path do %>
        <div class="item">
          <p>Language</p>
          <p>プログラミング言語の追加・削除</p>
        </div>
        <% end %>
      </div>
    </div>
  </div>
</div>