config/routes.rb
Rails.application.routes.draw do
  get 'notifications/index'
  get 'rooms/show'
  get 'events/index'
  devise_for :users , controllers: {
    sessions: 'users/sessions',
    passwords: 'users/passwords',
    registrations: 'users/registrations'
  }
  devise_for :admins, controllers: {
    sessions: 'admins/sessions',
    passwords: 'admins/passwords',
    registrations: 'admins/registrations'
  }

  namespace :admins do
    get "prefectures/search" => "prefectures#search"
    resources :prefectures, only: [:index, :show, :create ]
    get 'contacts/top' => "contacts#top"
    resources :contacts, except: :show
    resources :language_tags, except: :show
    resources :framework_tags, except: :show
    resources :companies
    resources :post_comments, only: [:index, :show, :destroy]
  end
  namespace :api, format: 'json' do
    resources :memos, only: [:index, :create, :destroy, :update]
    resources :tasks, only: [:index, :create, :update, :destroy]
  end

  root to: 'homes#top'
  get "homes/about" => "homes#about"
  get "homes/memo" => "homes#memo"
  get "homes/community" => "homes#community"
  get "homes/task" => "homes#task"
  get "task_about" => "contacts#task"
  get "task_top" => "contacts#task"
  get "prefectures/search" => "prefectures#search"
  resources :contacts, only: [:new, :create]
  resources :prefectures, only: [:index, :show]
  resources :companies, only: :show do
    resources :post_comments, except: [:index ,:show]
  end
  resources :events
  resources :users, only: :show
  resources :communities, only: [:index, :show, :create ,:destroy] do
    resource :likes, only: [:create, :destroy]
  end
  resources :chat_rooms, only: [:show, :create ]
  resources :chat_messages, only: :create
  resources :notifications, only: [:index]
  delete "notifications/destroy_all" => "notifications#destroy_all"

  mount ActionCable.server => '/cable'
end

app/models/company.rb
class Company < ApplicationRecord
  belongs_to :prefecture
  mount_uploader :image, ImageUploader
  has_many :post_comments, dependent: :destroy
  has_many :company_language_tag_relations, dependent: :destroy
  has_many :company_framework_tag_relations, dependent: :destroy
  has_many :language_tags, through: :company_language_tag_relations, dependent: :destroy
  has_many :framework_tags, through: :company_framework_tag_relations, dependent: :destroy


  with_options presence: true do
    validates :company_name
    validates :description
    validates :phone_number
    validates :prefecture_id
  end

  def avg_score
    unless self.post_comments.empty?
      post_comments.average(:score).round(1).to_f
    else
      0.0
    end
  end

  def review_score_percentage
    unless self.post_comments.empty?
      post_comments.average(:score).round(1).to_f*100/5
    else
      0.0
    end
  end

  def self.search(search)
    if search
    Company.where(['company_name LIKE ?', "%#{search}%" ])
    else
      Company.all
    end
  end
end

app/controllers/admins/companies_controller.rb
class Admins::CompaniesController < ApplicationController
  before_action :authenticate_admin!
  before_action :set_user, except:[:new, :create, :index]
  def index
    @comments = PostComment.all
  end
  def show
    @reviews = @company.post_comments
  end

  def new
    @languages = LanguageTag.all
    @frameworks = FrameworkTag.all
    @company = Company.new
  end

  def create
    @company = Company.new(company_params)
    if @company.save
      flash[:notice] = 'successfully'
      redirect_to admins_prefectures_path
    else
      @languages = LanguageTag.all
      @frameworks = FrameworkTag.all
      render :new
    end
  end

  def update
    @company = Company.find(params[:id])
    @prefecture = @company.prefecture_id
    if @company.update(company_params)
      redirect_to admins_prefecture_path(@prefecture)
    else
      render :edit
    end

  end
  def destroy
    if @company.destroy
      redirect_to admins_prefecture_path(@company.prefecture_id)
    end
  end

  private

  def set_user
    @company = Company.find(params[:id])
  end

  def company_params
    params.require(:company).permit(:company_name, :description, :image, :prefecture_id, :address, :phone_number, :url, language_tag_ids: [], framework_tag_ids: [])
  end
end

app/controllers/companies_controller.rb
class CompaniesController < ApplicationController
  before_action :authenticate_user!, only: [:show]
  def index
    @companies = Company.search(params[:search])
  end

  def show
    @company = Company.find(params[:id])
    @reviews = @company.post_comments
  end
end

app/views/companies/show.html.erb
<div class="wrapper">
  <div class="prefectures">
    <div>
      <span class="back-link">
        <%= link_to prefecture_path(@company.prefecture_id) do %>
        <i class="fas fa-undo-alt"></i><%= @company.prefecture.prefecture_name %>の一覧ページ
        <% end %>
      </span>
      <div class="prefectures__company">
        <div class="prefectures__img">
          <% if @company.image? %>
          <%= image_tag @company.image.url %>
          <% else %>
          <%= image_tag asset_path("no-image.jpg") %>
          <% end %>

          <div class="left-item">
            <div class="star-rating">
              <div class="star-rating-front" style="width: <%= @company.review_score_percentage %>%">★★★★★</div>
              <div class="star-rating-back">★★★★★</div>
            </div>
            <div class="average-score-display">
              <%= @company.avg_score %>点（<%= @company.post_comments.count %>件のレビュー）
            </div>
            <%= link_to "レビューを書く", new_company_post_comment_path(@company), class: "btn solid"  %>
          </div>
        </div>
        <div class="prefectures__texts">
          <div class="prefectures__texts-inner">
            <div class="main-title"><%= @company.company_name %></div>
            <div>本社所在地 :<%= @company.address %></div>
            <div>電話番号 :<%= @company.phone_number %></div>
            <div>言語 :
              <% @company.language_tags.each do |tag| %>
              <span class="language"><%= tag.language  %></span>
              <% end %>
            </div>
            <div>フレームワーク :
              <% @company.framework_tags.each do |tag| %>
              <span class="language"><%= tag.framework  %></span>
              <% end %>
            </div>
            <div>概要 :<%= @company.description %></div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

<div class="review">
  <div class="review__inner">
    <% @reviews.each do |review| %>
    <div class="review__items">
      <div class="personal">
        <%= review.user.name %>・
        <%= review.gender %>・
        <%= review.employment_status %>
      </div>
      <div class="star-rating mb-2">
        <div class="star-rating-front" style="width: <%= review.self_score_percentage %>%">★★★★★</div>
        <div class="star-rating-back">★★★★★</div>
      </div>

      <div><%= review.score %>点</div>
      <div><%= review.comment %></div>
      <div class="review-time"><%= review.created_at.strftime("%Y年%m月%d日")  %></div>
      <% if review.user.id == current_user.id %>
      <div class="useronly">
        <%= link_to "編集",edit_company_post_comment_path(review.company.id,review) %>
        <%= link_to "削除",company_post_comment_path(review.company.id,review), method: :delete , data: {confirm: "Are you sure?"} %>
      </div>
      <% end %>
    </div>
    <% end %>
  </div>
</div>