config/routes.rb
Rails.application.routes.draw do
  get 'notifications/index'
  get 'rooms/show'
  get 'events/index'
  devise_for :users , controllers: {
    sessions: 'users/sessions',
    passwords: 'users/passwords',
    registrations: 'users/registrations'
  }
  devise_for :admins, controllers: {
    sessions: 'admins/sessions',
    passwords: 'admins/passwords',
    registrations: 'admins/registrations'
  }

  namespace :admins do
    get "prefectures/search" => "prefectures#search"
    resources :prefectures, only: [:index, :show, :create ]
    get 'contacts/top' => "contacts#top"
    resources :contacts, except: :show
    resources :language_tags, except: :show
    resources :framework_tags, except: :show
    resources :companies
    resources :post_comments, only: [:index, :show, :destroy]
  end
  namespace :api, format: 'json' do
    resources :memos, only: [:index, :create, :destroy, :update]
    resources :tasks, only: [:index, :create, :update, :destroy]
  end

  root to: 'homes#top'
  get "homes/about" => "homes#about"
  get "homes/memo" => "homes#memo"
  get "homes/community" => "homes#community"
  get "homes/task" => "homes#task"
  get "task_about" => "contacts#task"
  get "task_top" => "contacts#task"
  get "prefectures/search" => "prefectures#search"
  resources :contacts, only: [:new, :create]
  resources :prefectures, only: [:index, :show]
  resources :companies, only: :show do
    resources :post_comments, except: [:index ,:show]
  end
  resources :events
  resources :users, only: :show
  resources :communities, only: [:index, :show, :create ,:destroy] do
    resource :likes, only: [:create, :destroy]
  end
  resources :chat_rooms, only: [:show, :create ]
  resources :chat_messages, only: :create
  resources :notifications, only: [:index]
  delete "notifications/destroy_all" => "notifications#destroy_all"

  mount ActionCable.server => '/cable'
end

app/models/prefecture.rb
class Prefecture < ApplicationRecord
  has_many :companies, dependent: :destroy

  enum prefecture_name:{
    "---":0,
    北海道:1,青森県:2,岩手県:3,宮城県:4,秋田県:5,山形県:6,福島県:7,
    茨城県:8,栃木県:9,群馬県:10,埼玉県:11,千葉県:12,東京都:13,神奈川県:14,
    新潟県:15,富山県:16,石川県:17,福井県:18,山梨県:19,長野県:20,
    岐阜県:21,静岡県:22,愛知県:23,三重県:24,
    滋賀県:25,京都府:26,大阪府:27,兵庫県:28,奈良県:29,和歌山県:30,
    鳥取県:31,島根県:32,岡山県:33,広島県:34,山口県:35,
    徳島県:36,香川県:37,愛媛県:38,高知県:39,
    福岡県:40,佐賀県:41,長崎県:42,熊本県:43,大分県:44,宮崎県:45,鹿児島県:46,
    沖縄県:47
  }
end

app/controllers/admins/prefectures_controller.rb
class Admins::PrefecturesController < ApplicationController
  before_action :authenticate_admin!
  def index
    @languages = LanguageTag.all
    @frameworks = FrameworkTag.all
  end

  def show
    @prefecture = Prefecture.find(params[:id])
    @companies = @prefecture.companies
  end

  def search
    if params[:search].present?
      @companies = Company.search(params[:search])
    elsif params[:language_tag_id].present?
      @companies = LanguageTag.find(params[:language_tag_id]).companies
    else
      @companies = FrameworkTag.find(params[:framework_tag_id]).companies
    end
  end

  def destroy
    @prefecture = Prefecture.find(params[:id])
    @company = Company.find(params[:id])
    if@company.destroy
      redirect_to admins_prefecture_path(@prefecture)
    end
  end
end

app/controllers/prefectures_controller.rb
class PrefecturesController < ApplicationController
  def index
    @languages = LanguageTag.all
    @frameworks = FrameworkTag.all
  end

  def show
    @prefecture = Prefecture.find(params[:id])
    @companies = @prefecture.companies
  end

  def search
    if params[:search].present?
      @companies = Company.search(params[:search])
    elsif params[:language_tag_id].present?
      @companies = LanguageTag.find(params[:language_tag_id]).companies
    else
      @companies = FrameworkTag.find(params[:framework_tag_id]).companies
    end
  end
end

app/views/admins/prefectures/index.html.erb
<div class="wrapper">
  <div class="prefectures row">
    <div class="col-lg-8">
      <%= link_to '掲載企業の追加・編集',new_admins_company_path , class: "btn solid" %>

      <div class="prefectures__inner">
        <div class="prefectures__group">
          <div class="prefectures__group-title">
            <span>北海道・東北</span>
          </div>
          <ul class="prefectures__ul">
            <li> <%= link_to "北海道", admins_prefecture_path(1) %></li>
            <li> <%= link_to "青森県", admins_prefecture_path(2) %></li>
            <li><%= link_to "岩手県", admins_prefecture_path(3) %></li>
            <li><%= link_to "宮城県", admins_prefecture_path(4) %></li>
            <li><%= link_to "秋田県", admins_prefecture_path(5) %></li>
            <li><%= link_to "山形県", admins_prefecture_path(6) %></li>
            <li><%= link_to "福島県", admins_prefecture_path(7) %></li>
          </ul>
        </div>
        <div class="prefectures__group">
          <div class="prefectures__group-title">
            <span>関東</span>
          </div>
          <ul class="prefectures__ul">
            <li><%= link_to "東京都", admins_prefecture_path(13) %></li>
            <li><%= link_to "神奈川県", admins_prefecture_path(14) %></li>
            <li><%= link_to "千葉県", admins_prefecture_path(12) %></li>
            <li><%= link_to "埼玉県", admins_prefecture_path(11) %></li>
            <li><%= link_to "茨城県", admins_prefecture_path(8) %></li>
            <li><%= link_to "栃木県", admins_prefecture_path(9) %></li>
            <li><%= link_to "群馬県", admins_prefecture_path(10) %></li>
          </ul>
        </div>
        <div class="prefectures__group">
          <div class="prefectures__group-title">
            <span>中部</span>
          </div>
          <ul class="prefectures__ul">
            <li><%= link_to "愛知県", admins_prefecture_path(23) %></li>
            <li><%= link_to "山梨県", admins_prefecture_path(15) %></li>
            <li><%= link_to "長野県", admins_prefecture_path(16) %></li>
            <li><%= link_to "新潟県", admins_prefecture_path(17) %></li>
            <li><%= link_to "富山県", admins_prefecture_path(18) %></li>
            <li><%= link_to "石川県", admins_prefecture_path(19) %></li>
            <li><%= link_to "福井県", admins_prefecture_path(20) %></li>
            <li><%= link_to "岐阜県", admins_prefecture_path(21) %></li>
            <li><%= link_to "静岡県", admins_prefecture_path(22) %></li>
            <li><%= link_to "三重県", admins_prefecture_path(24) %></li>
          </ul>
        </div>
        <div class="prefectures__group">
          <div class="prefectures__group-title">
            <span>関西</span>
          </div>
          <ul class="prefectures__ul">
            <li><%= link_to "大阪府", admins_prefecture_path(27) %></li>
            <li><%= link_to "京都府", admins_prefecture_path(26) %></li>
            <li><%= link_to "滋賀県", admins_prefecture_path(25) %></li>
            <li><%= link_to "兵庫県", admins_prefecture_path(28) %></li>
            <li><%= link_to "奈良県", admins_prefecture_path(29) %></li>
            <li><%= link_to "和歌山県", admins_prefecture_path(30) %></li>
          </ul>
        </div>
        <div class="prefectures__group">
          <div class="prefectures__group-title">
            <span>中国・四国</span>
          </div>
          <ul class="prefectures__ul">
            <li><%= link_to "広島県", admins_prefecture_path(34) %></li>
            <li><%= link_to "鳥取県", admins_prefecture_path(31) %></li>
            <li><%= link_to "島根県", admins_prefecture_path(32) %></li>
            <li><%= link_to "岡山県", admins_prefecture_path(33) %></li>
            <li><%= link_to "山口県", admins_prefecture_path(35) %></li>
            <li><%= link_to "徳島県", admins_prefecture_path(36) %></li>
            <li><%= link_to "香川県", admins_prefecture_path(37) %></li>
            <li><%= link_to "愛媛県", admins_prefecture_path(38) %></li>
            <li><%= link_to "高知県", admins_prefecture_path(39) %></li>
          </ul>
        </div>
        <div class="prefectures__group">
          <div class="prefectures__group-title">
            <span>九州・沖縄</span>
          </div>
          <ul class="prefectures__ul">
            <li><%= link_to "福岡県", prefecture_path(40) %></li>
            <li><%= link_to "滋賀県", prefecture_path(41) %></li>
            <li><%= link_to "長崎県", prefecture_path(42) %></li>
            <li><%= link_to "熊本県", prefecture_path(43) %></li>
            <li><%= link_to "大分県", prefecture_path(44) %></li>
            <li><%= link_to "宮崎県", prefecture_path(45) %></li>
            <li><%= link_to "鹿児島県", prefecture_path(46) %></li>
            <li><%= link_to "沖縄県", prefecture_path(47) %></li>
          </ul>
        </div>
      </div>
    </div>
    <div class="search-box col-lg-4 item">
      <div class="search-box__inner">
        <div class="name-search">
          <%= form_tag(admins_prefectures_search_path, :method => "get") do %>
          <%= text_field_tag :search ,'', placeholder: "会社名を入力"%>
          <%= submit_tag "Search" %>
          <% end %>
        </div>
        <div class="tag-search">
          <%= form_tag( admins_prefectures_search_path, :method => "get") do %>
          <%= select_tag :language_tag_id,  options_from_collection_for_select(@languages, :id, :language, params[:language_tag_id]), prompt:  'プログラミング言語で絞り込み' %>
          <%= submit_tag "Search" %>
          <% end %>

          <%= form_tag(admins_prefectures_search_path, :method => "get") do %>
          <%= select_tag :framework_tag_id,  options_from_collection_for_select(@frameworks, :id, :framework, params[:framework_tag_id]), prompt:  'フレームワークで絞り込み'%>
          <%= submit_tag "Search" %>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/admins/prefectures/search.html.erb
<div class="wrapper">
  <div class="prefectures">
    <% if @companies.present? %>
    <div class="prefectures-show">
      <span class="back-link">
        <%= link_to admins_prefectures_path do %>
        <i class="fas fa-undo-alt"></i>都道府県一覧ページ
        <% end %>
      </span>
      <% @companies.each do |company| %>
      <div class="prefectures__company">
        <div class="prefectures__img">
          <% if company.image? %>
          <%= image_tag company.image.url %>
          <% else %>
          <%= image_tag "no-image.jpg" %>
          <% end %>
          <div class="star-rating">
            <div class="star-rating-front" style="width: <%= company.review_score_percentage %>%">★★★★★</div>
            <div class="star-rating-back">★★★★★</div>
          </div>
          <div class="average-score-display">
            <%= company.avg_score %>点（<%= company.post_comments.count %>件のレビュー）
          </div>
          <button class="btn solid"><%= link_to '詳しく見る', company_path(company) %>
        </div>
        <div class="prefectures__texts">
          <div class="prefectures__texts-inner">
            <div class="main-title"><%= company.company_name %></div>
            <div>本社所在地 :<%= company.address %></div>
            <div>電話番号 :<%= company.phone_number %></div>
            <div>言語 :
              <% company.language_tags.each do |tag| %>
              <span class="language"><%= tag.language  %></span>
              <% end %>
            </div>
            <div>フレームワーク :
              <% company.framework_tags.each do |tag| %>
              <span class="language"><%= tag.framework  %></span>
              <% end %>
            </div>
            <div>概要 :<%= company.description %></div>
          </div>
        </div>
      </div>
      <% end %>
    </div>
    <% else %>
    検索対象の会社は存在しません。
    <% end %>
  </div>
</div>

app/views/admins/prefectures/show.html.erb
<div class="wrapper">
  <div class="prefectures">
    <div class="prefectures-show">
      <div class="prefectures__title main-title">
        <%= @prefecture.prefecture_name + "のWEB系企業を探す" %>
      </div>
      <span class="back-link">
        <%= link_to admins_prefectures_path do %>
        <i class="fas fa-undo-alt"></i>都道府県一覧ページ
        <% end %>
      </span>
      <% if @companies.present?  %>
      <% @companies.each do |company| %>
      <div class="prefectures__company">
        <div class="prefectures__img">
          <% if company.image? %>
          <%= image_tag company.image.url %>
          <% else %>
          <%= image_tag asset_path("no-image.jpg") %>
          <% end %>

          <div class="star-rating">
            <div class="star-rating-front" style="width: <%= company.review_score_percentage %>%">★★★★★</div>
            <div class="star-rating-back">★★★★★</div>
          </div>
          <div class="average-score-display">
            <%= company.avg_score %>点（<%= company.post_comments.count %>件のレビュー）
          </div>
          <%= link_to 'レビューを見る', admins_company_path(company) , class: "btn solid" %>
        </div>

        <div class="prefectures__texts">
          <div class="prefectures__texts-inner">
            <div class="main-title"><%= company.company_name %>
              <span class="link-item">
                <%= link_to edit_admins_company_path(company) ,class: "edit" do %>
                <i class="fas fa-tools"></i>
                <% end %>:
                <%= link_to admins_company_path(company),method: :delete, data: {confirm: "Are you sure?"} do %>
                <i class="fas fa-trash"></i>
                <% end %>
              </span>
            </div>
            <div>本社所在地 :<%= company.address %></div>
            <div>電話番号 :<%= company.phone_number %></div>
            <div>言語 :
              <% company.language_tags.each do |tag| %>
              <span class="language"><%= tag.language  %></span>
              <% end %>
            </div>
            <div>フレームワーク :
              <% company.framework_tags.each do |tag| %>
              <span class="language"><%= tag.framework  %></span>
              <% end %>
            </div>
            <div>概要 :<%= company.description %></div>
          </div>
        </div>
      </div>
      <% end %>
      <% else %>
      現在、掲載企業はありません。
      <% end %>
    </div>
  </div>
</div>